services:
  neo4j-db:
    image: neo4j:latest
    container_name: intellicase_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j_data:/data

  streamlit-app:
    build: .
    container_name: intellicase_app
    ports:
      - "8501:8501"
    depends_on:
      - neo4j-db
    environment:
      - NEO4J_URI=bolt://neo4j-db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - .:/app
